version: "3.9"
name: inception

services:

  nginx:
    container_name: nginx
    build:
      context:  ./requirements/nginx

  wordpress:
    container_name: wordpress
    build:
      context:  ./requirements/wordpress

  mariadb:
    container_name: mariadb
    build:
      context:  ./requirements/mariadb

volumes:

  wordpress_db:

  wordpress_data:

network:

  name: inception
  driver: bridge
