version: '3.9'
name: inception

services:

  nginx:
    container_name: nginx

  wordpress:
    container_name: wordpress

  mariadb:
    container_name: mariadb

volumes:

  wp_db:

  wp_data:

network:


