version: "3.9"

services:

  nginx:
    container_name: nginx
    image: nginx
    build:
      context: ./requirements/nginx
    ports:
      - "433:433"
    networks:
      - inception
    restart: on-failure
    volumes:
      - database:/var/www/html
    depends_on: wordpress

  wordpress:
    container_name: wordpress
    image: wordpress
    build:
      context: ./requirements/wordpress
    networks:
      - inception
    restart: on-failure
    volumes:
      - website:/var/www/html
    depends_on: mariadb

  mariadb:
    container_name: mariadb
    image: mariadb
    build:
      context: ./requirements/mariadb
    networks:
      - inception
    restart: on-failure
    volumes:
      - database:/var/lib/mysql

secrets:

volumes:

  database:

  website:

networks:

  inception:
    driver: bridge
