version: "3.9"
name: inception

services:

  nginx:
    container_name: nginx
    build:
      context:  ./requirements/nginx
    ports:
      - "433:433"
    restart:  on-failure

  wordpress:
    container_name: wordpress
    build:
      context:  ./requirements/wordpress
    restart:  on-failure

  mariadb:
    container_name: mariadb
    build:
      context:  ./requirements/mariadb
    restart:  on-failure

volumes:

  wordpress_db:

  wordpress_data:

# TODO: lire plus de documentation sur le sujet
networks:

  inception:
    name: inception
    driver: bridge
