version: "3.9"

services:

  nginx:
    container_name: nginx
    image:  nginx
    build:
      context:  ./requirements/nginx
    ports:
      - "433:433"
    networks:
      - inception
    restart:  on-failure

  wordpress:
    container_name: wordpress
    image:  wordpress
    build:
      context:  ./requirements/wordpress
    networks:
      - inception
    restart:  on-failure

  mariadb:
    container_name: mariadb
    image:  mariadb
    build:
      context:  ./requirements/mariadb
    networks:
      - inception
    restart:  on-failure

volumes:

  wordpress_db:

  wordpress_data:

# TODO: lire plus de documentation sur le sujet
networks:

  inception:
    driver: bridge
