# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mmosca <mmosca@student.42lyon.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/05/02 15:04:36 by mmosca            #+#    #+#              #
#    Updated: 2022/05/02 15:17:04 by mmosca           ###   ########lyon.fr    #
#                                                                              #
# **************************************************************************** #

## ~~~~ Operating System ~~~~ ##
FROM alpine:3.14

## ~~~~ Image's metadatas ~~~~ ##
LABEL version="1.0" maintainer="MOSCA Marc <mmosca@student42lyon.fr>"
